// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package line

const (
	propCount             uint8 = 108
	lastCodepointProperty uint8 = 91
	pSOT                  uint8 = 106
	pEOT                  uint8 = 107
	pSA                   uint8 = 41
)
