// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package line

const (
	propCount             uint8 = 122
	lastCodepointProperty uint8 = 105
	pSOT                  uint8 = 120
	pEOT                  uint8 = 121
	pSA                   uint8 = 41

	pBK uint8 = 1
	pCR uint8 = 2
	pLF uint8 = 3
	pNL uint8 = 4
)
