// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package word

const (
	propCount             uint8 = 36
	lastCodepointProperty uint8 = 28
	pSOT                  uint8 = 34
	pEOT                  uint8 = 35

	pALetter      uint8 = 10
	pHebrewLetter uint8 = 9
	pKatakana     uint8 = 8
	pExtendNumLet uint8 = 17
	pNumeric      uint8 = 16

	pALetter_ZWJ      uint8 = 21
	pHebrewLetter_ZWJ uint8 = 22
	pNumeric_ZWJ      uint8 = 23
	pKatakana_ZWJ     uint8 = 24
	pExtendNumLet_ZWJ uint8 = 25
)
