// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package word

// Property indices for word break.
//
// Base properties 0–19 correspond to Word_Break property values from the
// Unicode Character Database, with the addition of Extended_Pictographic
// (needed for WB3c). The gen.go generator assigns these indices when
// building the property trie.
//
// Absorption states (_ZWJ variants, WSegSpace_XX) implement WB4.
// They have indices ≤ lastCodepointProperty, so the engine advances
// the marker past each absorbed character.
//
// Lookahead states implement multi-character rules: WB6/7, WB7b/7c,
// WB11/12, and WB15/16. These have indices > lastCodepointProperty,
// so the engine does NOT advance the marker on entry — NoMatch rewinds.
//
// SOT and EOT are virtual properties for start-of-text and end-of-text.
const (
	pOther             uint8 = iota // WB=Other
	pCR                             // WB=CR
	pLF                             // WB=LF
	pNewline                        // WB=Newline
	pExtend                         // WB=Extend
	pZWJ                            // WB=ZWJ
	pFormat                         // WB=Format
	pRegionalIndicator              // WB=Regional_Indicator
	pKatakana                       // WB=Katakana
	pHebrewLetter                   // WB=Hebrew_Letter
	pALetter                        // WB=ALetter
	pSingleQuote                    // WB=Single_Quote
	pDoubleQuote                    // WB=Double_Quote
	pMidLetter                      // WB=MidLetter
	pMidNum                         // WB=MidNum
	pMidNumLet                      // WB=MidNumLet
	pNumeric                        // WB=Numeric
	pExtendNumLet                   // WB=ExtendNumLet
	pExtPict                        // Extended_Pictographic=Yes
	pWSegSpace                      // WB=WSegSpace
	lastBaseProperty   = pWSegSpace
)

// WB4 absorption states. _XX means Extend/Format was absorbed (WSegSpace
// loses WB3d eligibility). _ZWJ means ZWJ was the most recent absorbed
// character (needed for WB3c).
const (
	pWSegSpace_XX uint8 = lastBaseProperty + 1 + iota
	pALetter_ZWJ
	pHebrewLetter_ZWJ
	pNumeric_ZWJ
	pKatakana_ZWJ
	pExtendNumLet_ZWJ
	pRegionalIndicator_ZWJ
	pExtPict_ZWJ
	pWSegSpace_ZWJ
	lastCodepointProperty = pWSegSpace_ZWJ
)

// Lookahead and virtual property states.
const (
	pAHL_MidLetter uint8 = lastCodepointProperty + 1 + iota // AHLetter × (MidLetter|MidNumLetQ) (WB6/7)
	pHL_MidLetter                                           // HebrewLetter × (MidLetter|MidNumLetQ) (WB6/7)
	pNum_MidNum                                             // Numeric × (MidNum|MidNumLetQ) (WB11/12)
	pHL_DQ                                                  // HebrewLetter × Double_Quote (WB7b/7c)
	pRI_RI                                                  // RI × RI pair consumed (WB15/16)
	pSOT                                                    // start of text
	pEOT                                                    // end of text
	propCount                                               // total property count (stride)
)
