// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package sentence

const (
	propCount             uint8 = 33
	lastCodepointProperty uint8 = 23
	pSOT                  uint8 = 31
	pEOT                  uint8 = 32

	pLower   uint8 = 7
	pUpper   uint8 = 8
	pNumeric uint8 = 10
	pSp      uint8 = 6
)
