// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package sentence

// Property indices for sentence break.
//
// Base properties 0–14 correspond to Sentence_Break property values from the
// Unicode Character Database. The gen.go generator assigns these indices when
// building the property trie.
//
// Absorption states (15–23) are synthetic properties created by SB5
// absorption (X × Extend/Format → X) and SB7 context tracking. These have
// indices ≤ lastCodepointProperty, so the engine advances the marker past
// each absorbed character.
//
// Chain states (24–30) implement multi-character rules SB8–SB11 using
// the engine's combined-state mechanism. Chain state rows default to NoMatch
// so that unmatched transitions cause the engine to rewind to the marker
// position (the SB11 break point).
//
// SOT and EOT are virtual properties for start-of-text and end-of-text.

// Base properties from UCD.
const (
	pOther     uint8 = iota // SB=Other
	pCR                     // SB=CR
	pLF                     // SB=LF
	pSep                    // SB=Sep
	pExtend                 // SB=Extend
	pFormat                 // SB=Format
	pSp                     // SB=Sp
	pLower                  // SB=Lower
	pUpper                  // SB=Upper
	pOLetter                // SB=OLetter
	pNumeric                // SB=Numeric
	pATerm                  // SB=ATerm
	pSTerm                  // SB=STerm
	pSContinue              // SB=SContinue
	pClose                  // SB=Close

	lastBaseProperty = pClose
)

// Absorption states: base property after absorbing Extend/Format (SB5).
// Indices ≤ lastCodepointProperty so the engine moves the marker.
const (
	pLower_XX   uint8 = lastBaseProperty + 1 + iota // Lower after absorbing Extend/Format
	pUpper_XX                                       // Upper after absorbing Extend/Format
	pOLetter_XX                                     // OLetter after absorbing Extend/Format
	pNumeric_XX                                     // Numeric after absorbing Extend/Format
	pATerm_XX                                       // ATerm after absorbing Extend/Format
	pSTerm_XX                                       // STerm after absorbing Extend/Format
	pSCont_XX                                       // SContinue after absorbing Extend/Format
	pClose_XX                                       // Close after absorbing Extend/Format

	// SB7 context: (Upper|Lower) × ATerm → pUL_ATerm.
	// Absorption state (≤ lastCodepointProperty) so the engine advances the
	// marker past the ATerm.
	pUL_ATerm

	lastCodepointProperty = pUL_ATerm
)

// Chain states for multi-character rules SB8–SB11 and virtual properties.
const (
	// ATerm chain: ATerm Close* Sp* (SB9/SB10/SB11/SB8)
	pATerm_Close uint8 = lastCodepointProperty + 1 + iota // ATerm Close*
	pATerm_Sp                                             // ATerm Close* Sp*
	pATerm_Scan                                           // ATerm Close* Sp* (scan chars)* — SB8 forward scan
	pATerm_Para                                           // ATerm Close* Sp* ParaSep — SB11 pending

	// STerm chain: STerm Close* Sp* (SB9/SB10/SB11)
	pSTerm_Close // STerm Close*
	pSTerm_Sp    // STerm Close* Sp*
	pSTerm_Para  // STerm Close* Sp* ParaSep — SB11 pending

	// Virtual properties.
	pSOT      // start of text
	pEOT      // end of text
	propCount // total number of properties (= stride)
)
