// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package grapheme

const (
	propCount             uint8 = 24
	lastCodepointProperty uint8 = 21
	pSOT                  uint8 = 22
	pEOT                  uint8 = 23
)
