// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package grapheme

import "golang.org/x/text/internal/segmenter"

// Property indices for grapheme cluster break.
//
// Base properties 0–17 correspond to Grapheme_Cluster_Break values from
// the Unicode Character Database, with InCB (Indic_Conjunct_Break) sub-properties
// split out from Extend for rule GB9c. The gen.go generator assigns these
// indices when building the property trie.
//
// Combined states 18–21 are synthetic properties used by the state machine
// to track multi-character lookahead contexts (GB11, GB12/13, GB9c).
//
// SOT and EOT are virtual properties for start-of-text and end-of-text.
const (
	pOther             uint8 = iota // GCB=Other (and InCB=None)
	pCR                             // GCB=CR
	pLF                             // GCB=LF
	pControl                        // GCB=Control
	pExtend                         // GCB=Extend (and InCB=None)
	pZWJ                            // GCB=ZWJ (U+200D)
	pRegionalIndicator              // GCB=Regional_Indicator
	pPrepend                        // GCB=Prepend
	pSpacingMark                    // GCB=SpacingMark
	pL                              // GCB=L (Hangul leading jamo)
	pV                              // GCB=V (Hangul vowel jamo)
	pT                              // GCB=T (Hangul trailing jamo)
	pLV                             // GCB=LV (Hangul LV syllable)
	pLVT                            // GCB=LVT (Hangul LVT syllable)
	pExtPict                        // Extended_Pictographic=Yes
	pInCBLinker                     // InCB=Linker (subset of GCB=Extend; viramas)
	pInCBConsonant                  // InCB=Consonant (subset of GCB=Other; Indic consonants)
	pInCBExtend                     // InCB=Extend (subset of GCB=Extend; combining marks near Indic clusters)

	// Combined states for multi-character lookahead.
	pRI_RI       // after RI × RI (GB12/13: pair consumed)
	pExtPict_Ext // after ExtPict × Extend* (GB11: accumulating extends)
	pExtPict_ZWJ // after ExtPict × Extend* × ZWJ (GB11: ready for next ExtPict)
	pInCB_Linker // after Consonant × [Extend|Linker]* × Linker (GB9c)

	// Virtual properties.
	pSOT      // start of text
	pEOT      // end of text
	propCount // total number of properties (= stride)
)

const lastCodepointProperty = pInCB_Linker

// rules encodes the UAX #29 grapheme cluster boundary rules (GB3–GB999)
// as input to [segmenter.BuildStateTable]. Rules are listed in priority
// order; the first match wins. Combined states handle GB9c, GB11, and
// GB12/13 lookahead.
//
// References: https://www.unicode.org/reports/tr29/#Grapheme_Cluster_Boundary_Rules
var rules = []segmenter.Rule{
	// GB1: sot ÷ Any — implicit; the segmenter always starts at position 0.
	// In the state table SOT × Any = Keep so the engine's SOT handling
	// consumes the first character and enters the main loop. This must
	// precede GB4/GB5 whose wildcards would otherwise match SOT.
	{Left: p(pSOT), Right: nil, Break: false},

	// GB2: Any ÷ eot — always break at end of text.
	// The engine handles EOT explicitly, but this rule ensures the EOT
	// column of the state table is filled with Break for all left properties.
	{Left: nil, Right: p(pEOT), Break: true},

	// GB3: CR × LF — do not break between CR and LF.
	{Left: p(pCR), Right: p(pLF), Break: false},

	// GB4: (Control | CR | LF) ÷ — break after controls.
	{Left: p(pControl, pCR, pLF), Right: nil, Break: true},

	// GB5: ÷ (Control | CR | LF) — break before controls.
	{Left: nil, Right: p(pControl, pCR, pLF), Break: true},

	// GB6: L × (L | V | LV | LVT)
	{Left: p(pL), Right: p(pL, pV, pLV, pLVT), Break: false},

	// GB7: (LV | V) × (V | T)
	{Left: p(pLV, pV), Right: p(pV, pT), Break: false},

	// GB8: (LVT | T) × T
	{Left: p(pLVT, pT), Right: p(pT), Break: false},

	// GB9: × (Extend | ZWJ) — do not break before extending characters or ZWJ.
	// InCB=Extend and InCB=Linker are subsets of GCB=Extend, so they are
	// included here to preserve the GB9 no-break behavior.
	{Left: nil, Right: p(pExtend, pZWJ, pInCBExtend, pInCBLinker), Break: false},

	// GB9a: × SpacingMark
	{Left: nil, Right: p(pSpacingMark), Break: false},

	// GB9b: Prepend ×
	{Left: p(pPrepend), Right: nil, Break: false},

	// GB9c: \p{InCB=Consonant} [\p{InCB=Extend}\p{InCB=Linker}]* \p{InCB=Linker}
	//       [\p{InCB=Extend}\p{InCB=Linker}]* × \p{InCB=Consonant}
	// Handled via combined state pInCB_Linker (see combinedStates below).
	{Left: p(pInCB_Linker), Right: p(pInCBConsonant), Break: false},

	// GB11: \p{Extended_Pictographic} Extend* ZWJ × \p{Extended_Pictographic}
	// Handled via combined states pExtPict_Ext → pExtPict_ZWJ.
	{Left: p(pExtPict_ZWJ), Right: p(pExtPict), Break: false},

	// GB12/GB13: sot (RI RI)* RI × RI / [^RI] (RI RI)* RI × RI
	// Only pair RI characters; break before a third consecutive RI.
	{Left: p(pRegionalIndicator), Right: p(pRegionalIndicator), Break: false},
	{Left: p(pRI_RI), Right: p(pRegionalIndicator), Break: true},

	// GB999: Any ÷ Any — otherwise, break everywhere.
	{Left: nil, Right: nil, Break: true},
}

// combinedStates defines transitions into synthetic combined-state properties.
// These overlay the rule table to implement multi-character lookahead without
// backtracking.
var combinedStates = []segmenter.CombinedState{
	// GB12/13: RI × RI → enter pRI_RI (pair consumed; next RI will break).
	{Left: pRegionalIndicator, Right: pRegionalIndicator, State: pRI_RI},

	// GB11: ExtPict × Extend → enter pExtPict_Ext (accumulating extends).
	{Left: pExtPict, Right: pExtend, State: pExtPict_Ext},
	{Left: pExtPict, Right: pInCBExtend, State: pExtPict_Ext},
	// GB11: ExtPict_Ext × Extend → stay in pExtPict_Ext.
	{Left: pExtPict_Ext, Right: pExtend, State: pExtPict_Ext},
	{Left: pExtPict_Ext, Right: pInCBExtend, State: pExtPict_Ext},
	// GB11: ExtPict_Ext × ZWJ → enter pExtPict_ZWJ (ready for next ExtPict).
	{Left: pExtPict_Ext, Right: pZWJ, State: pExtPict_ZWJ},
	// GB11: ExtPict × ZWJ → enter pExtPict_ZWJ (no intervening Extend).
	{Left: pExtPict, Right: pZWJ, State: pExtPict_ZWJ},

	// GB9c: Consonant × Linker → enter pInCB_Linker.
	{Left: pInCBConsonant, Right: pInCBLinker, State: pInCB_Linker},
	// GB9c: InCB_Linker × Extend → stay (absorb extends within the cluster).
	{Left: pInCB_Linker, Right: pInCBExtend, State: pInCB_Linker},
	// GB9c: InCB_Linker × Linker → stay (multiple linkers allowed).
	{Left: pInCB_Linker, Right: pInCBLinker, State: pInCB_Linker},
}

func p(props ...uint8) []uint8 { return props }
